#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'

string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var/www/html;\n\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-available/default

sudo service nginx restart