#!/usr/bin/env bash
# Displays numbers 1-100, fizzbuzz on multiples of 3 and 5
# fizz on multiples of 3
# buzz on multiples of 5

for ((i=1; i<=100; i++)); do
	if ((i % 3 == 0)) && ((i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done

