#!/usr/bin/env bash
# Loops from 1-10 and print bad luck, good luck and Best school
# at 4, 8 and rest iterations respectively

i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
