#!/usr/bin/env bash
# Displays numbers 1-20, bad luck on 4,9,17 iterations
# for China, Japan, and Italy respective, else display number

i=1
while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac

	((i++))
done

